name: news_reading
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  intl: ^0.18.0
  flutter_secure_storage: ^9.1.1
  convex_bottom_bar: ^3.2.0
  flutter_tts: ^4.0.2
  translator: ^1.0.0
  comment_box: ^0.0.18
  flutter_local_notifications: ^17.1.2
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.1
  image: ^4.2.0
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/AbelRegular.ttf
          weight: 400
    - family: Mulish
      fonts:
        - asset: assets/fonts/MulishRegular.ttf
          weight: 400
