import 'package:flutter/material.dart';
import 'package:news_reading/pages/search_page/search_bar.dart';
import 'package:news_reading/pages/search_page/search_btn.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class SearchPage extends StatelessWidget {
  const SearchPage.Search({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Search(),
        ]),
      ),
    );
  }
}

class Search extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 512,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 41,
                top: 70,
                child: SizedBox(
                  width: 266,
                  height: 39,
                  child: Text(
                    'Search Article',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'iCiel Gotham',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),

              //article here

              // Positioned(
              //   left: 40,
              //   top: 336,
              //   child: Container(
              //     width: 295,
              //     height: 141,
              //     child: Stack(
              //       children: [
              //         Positioned(
              //           left: 0,
              //           top: 0,
              //           child: Container(
              //             width: 295,
              //             height: 141,
              //             decoration: ShapeDecoration(
              //               color: Colors.white,
              //               shape: RoundedRectangleBorder(
              //                 borderRadius: BorderRadius.circular(16),
              //               ),
              //               shadows: [
              //                 BoxShadow(
              //                   color: Color(0x0F5182FF),
              //                   blurRadius: 15,
              //                   offset: Offset(0, 10),
              //                   spreadRadius: 0,
              //                 )
              //               ],
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 112,
              //           top: 44,
              //           child: SizedBox(
              //             width: 163,
              //             child: Text(
              //               'Why Big Data Needs Thick Data?',
              //               style: TextStyle(
              //                 color: Color(0xFF0D253C),
              //                 fontSize: 14,
              //                 fontFamily: 'Avenir',
              //                 fontWeight: FontWeight.w500,
              //               ),
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 112,
              //           top: 20,
              //           child: Text(
              //             'BIG DATA',
              //             style: TextStyle(
              //               color: Color(0xFF376AED),
              //               fontSize: 14,
              //               fontFamily: 'Avenir',
              //               fontWeight: FontWeight.w800,
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 195,
              //           top: 105,
              //           child: Text(
              //             '1hr ago',
              //             style: TextStyle(
              //               color: Color(0xFF2D4379),
              //               fontSize: 12,
              //               fontFamily: 'Avenir',
              //               fontWeight: FontWeight.w500,
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 134,
              //           top: 105,
              //           child: Text(
              //             '2.1k',
              //             style: TextStyle(
              //               color: Color(0xFF2D4379),
              //               fontSize: 12,
              //               fontFamily: 'Avenir',
              //               fontWeight: FontWeight.w500,
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 0,
              //           top: 0,
              //           child: Container(
              //             width: 92,
              //             height: 141,
              //             decoration: ShapeDecoration(
              //               image: DecorationImage(
              //                 image: NetworkImage("https://via.placeholder.com/92x141"),
              //                 fit: BoxFit.fill,
              //               ),
              //               shape: RoundedRectangleBorder(
              //                 borderRadius: BorderRadius.circular(16),
              //               ),
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 112,
              //           top: 105,
              //           child: Container(
              //             width: 16,
              //             height: 16,
              //             clipBehavior: Clip.antiAlias,
              //             decoration: BoxDecoration(),
              //             child: FlutterLogo(),
              //           ),
              //         ),
              //         Positioned(
              //           left: 173,
              //           top: 105,
              //           child: Container(
              //             width: 16,
              //             height: 16,
              //             clipBehavior: Clip.antiAlias,
              //             decoration: BoxDecoration(),
              //             child: FlutterLogo(),
              //           ),
              //         ),
              //         Positioned(
              //           left: 259,
              //           top: 105,
              //           child: Container(
              //             width: 16,
              //             height: 16,
              //             clipBehavior: Clip.antiAlias,
              //             decoration: BoxDecoration(),
              //             child: FlutterLogo(),
              //           ),
              //         ),
              //       ],
              //     ),
              //   ),
              // ),

              Positioned(
                left: 40,
                top: 136,
                width: 300,
                child: MySearchBar(),
              ),

              Positioned(left: 40, top: 236, child: BtnEff()),

              // Positioned(
              //     child: HomePage()
              // )
            ],
          ),
        ),
      ],
    );
  }
}
