import 'package:flutter/material.dart';

import 'Content.dart';
import 'GlowingIMG.dart';
import 'SliderVariants/Variant1.dart';
import 'SliderVariants/Variant2.dart';
import 'SliderVariants/Variant3.dart';
import 'SliderVariants/Variant4.dart';

void main() {
  runApp(const OnBoarding());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class OnBoarding extends StatelessWidget {
  const OnBoarding({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Onboarding(),
        ]),
      ),
    );
  }
}

class Onboarding extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [

              Positioned(
                left: 0,
                top: 450,
                child: Container(
                  width: 375,
                  height: 324,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(28),
                        topRight: Radius.circular(28),
                      ),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x115182FF),
                        blurRadius: 32,
                        offset: Offset(0, -25),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),

              Positioned(
                left: 247,
                top: 693,
                child: Container(
                  width: 88,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 88,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: Color(0xFF376AED),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 32,
                        top: 18,
                        child: Container(
                          width: 24,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: FlutterLogo(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 50,
                child: Container(
                  width: 294.94,
                  height: 332.56,
                  child: Stack(
                    children: [
                      GlowingImage(
                        imageUrl: 'https://via.placeholder.com/192x221',
                        width: 170.81,
                        height: 157.61,
                        left: 124.12,
                        top: 0,
                      ),
                      GlowingImage(
                        imageUrl: 'https://via.placeholder.com/192x221',
                        width: 190.82,
                        height: 157.81,
                        left: 0,
                        top: 174.75,
                      ),

                      GlowingImage(
                        imageUrl: 'https://via.placeholder.com/160x160',
                        width: 115,
                        height: 160,
                        left: 0,
                        top: 0,
                      ),


                      GlowingImage(
                        imageUrl: 'https://via.placeholder.com/160x160',
                        width: 92.12,
                        height: 157.75,
                        left: 202.82,
                        top: 174.75,
                      ),

                    ],
                  ),
                ),
              ),

              Positioned(
                left: 21,
                top: 423,
                child: Container(
                  width: 395,
                  height: 400,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        height: 300,
                        child: Content(),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
